import { useEffect, useState } from "react";
import type { OpportunityCard } from "../types";

export function EmailDrawer({
  card,
  groupLabel,
  actioned,
  onClose,
  onToggleActioned,
}: {
  card: OpportunityCard;
  groupLabel: string;
  actioned: boolean;
  onClose: () => void;
  onToggleActioned: () => void;
}) {
  const [status, setStatus] = useState<string | null>(null);

  useEffect(() => {
    function onKeydown(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    document.addEventListener("keydown", onKeydown);
    return () => document.removeEventListener("keydown", onKeydown);
  }, [onClose]);

  async function handleCopy() {
    const text = `Subject: ${card.subject}\n\n${card.body}`;
    try {
      await navigator.clipboard.writeText(text);
      setStatus("Email copied to clipboard.");
    } catch {
      setStatus("Could not copy — select the text above manually.");
    }
  }

  return (
    <>
      <div className="opp-scrim" onClick={onClose} />
      <aside className="opp-drawer" role="dialog" aria-modal="true">
        <div className="opp-drawer-header">
          <span className="opp-drawer-eyebrow">
            {groupLabel} · {card.customer_name}
          </span>
          <button className="opp-drawer-close" onClick={onClose} aria-label="Close email draft">
            ×
          </button>
        </div>
        <div className="opp-drawer-body">
          <h2>{card.subject}</h2>
          <dl className="opp-drawer-meta">
            <dt>To</dt>
            <dd>{card.recipient_name}</dd>
            <dt>Role</dt>
            <dd>{card.recipient_role}</dd>
            <dt>Account</dt>
            <dd>{card.customer_name}</dd>
          </dl>
          <div className="opp-drawer-email-body">{card.body}</div>
          <p className="opp-drawer-source">Static template — pre-written, not generated by an LLM</p>
          <div className="opp-drawer-actions">
            <button className="opp-btn opp-btn-primary" onClick={handleCopy}>
              Copy email
            </button>
            <button className="opp-btn" aria-pressed={actioned} onClick={onToggleActioned}>
              {actioned ? "Actioned ✓" : "Mark as actioned"}
            </button>
          </div>
          {status && <p className="opp-drawer-status">{status}</p>}
        </div>
      </aside>
    </>
  );
}
